export const wrapper: string
export const container: string
export const container__hero: string
export const container__hero__title: string
export const container__episodes: string
export const container__episodes__item: string
export const footer: string
export const footer__host: string
export const footer__host__title: string
export const footer__host__hosts: string
export const footer__host__hosts__item: string
